machine:
  node:
    version: 7.7.4
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

dependencies:
  override:
    - npm install
  cache_directories:
    - ~/.cache/yarn
test:
  override:
    - yarn lint
    - yarn test

deployment:
  staging:
    branch: master
    heroku:
appname: timetemp-react # appname must not include upper-case characters
